### ISSUE TITLE
Fatal error in WordPress 6.5.4

### ISSUE THREAD

**Issue by Intevel** [plausible/wordpress#217]
## Introduction
Installing official Plausible wordpress plugin on the WP Plugin Dashboard, crashes directly and goes in recovery mode.

## System Informations
WP Version: 6.5.4
Plugin Version: Latest
Language of Page: de_DE
Theme: Twenty Twenty-Four (twentytwentyfour) 1.1
PHP-Version 7.4.33

## Error
```
/var/customers/webs/my-user/webseite/wp-content/plugins/plausible-analytics/src/Client/lib/Lib/GuzzleHttp/Utils.php verursacht. Fehlermeldung: Uncaught RuntimeException: Plausible\Analytics\WP\Client\Lib\GuzzleHttp requires cURL, the allow_url_fopen ini setting, or a custom HTTP handler. in /var/customers/webs/my-user/webseite/wp-content/plugins/plausible-analytics/src/Client/lib/Lib/GuzzleHttp/Utils.php:105 Stack trace: #0 /var/customers/webs/my-user/webseite/wp-content/plugins/plausible-analytics/src/Client/lib/Lib/GuzzleHttp/HandlerStack.php(49): Plausible\Analytics\WP\Client\Lib\GuzzleHttp\Utils::chooseHandler() #1 /var/customers/webs/my-user/webseite/wp-content/plugins/plausible-analytics/src/Client/lib/Lib/GuzzleHttp/Client.php(53): Plausible\Analytics\WP\Client\Lib\GuzzleHttp\HandlerStack::create() #2 /var/customers/webs/my-user/webseite/wp-content/plugins/plausible-analytics/src/Client.php(39): Plausible\Analytics\WP\Client\Lib\GuzzleHttp\Client->__construct() #3 /var/customers/webs/my-user/webseite/wp-content/plugins/plausible-analytics/src/Admin/Settings/Page.php(80): Plausible\Analytics\WP\Client->_
```

**Comment by Dan0sz** [comment]
Thanks for reporting this! Will start working on this soon and I'm expecting a fix to be included in 2.1.0 which will be released soon (before the end of this month if all goes well)
